$(function(){
  $('section#landing').html(Handlebars.templates.landing(EN_CONTENT))
  $('section#intro').html(Handlebars.templates.intro(EN_CONTENT))
  $('section#camping').html(Handlebars.templates.camping(EN_CONTENT))
  $('section#hiking').html(Handlebars.templates.hiking(EN_CONTENT))
  $('section#pricing').html(Handlebars.templates.pricing(EN_CONTENT))
  $('section#team').html(Handlebars.templates.team(EN_CONTENT))
  $('section#gallery').html(Handlebars.templates.gallery(EN_CONTENT))
  $('section#contact').html(Handlebars.templates.contact(EN_CONTENT))
});